config/routes.rb
Rails.application.routes.draw do

  root to: 'food_trucks#index'

  devise_for :users

  resources :food_trucks, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    resources :votes, only: [:create]
  end

  namespace :admin do
    root to: 'food_trucks#index'
    resources :food_trucks, only: [:index, :show, :destroy]
    resources :reviews, only: [:destroy]
  end
end

app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  has_many :locations
  has_many :reviews, dependent: :destroy, counter_cache: true
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :user_id, presence: true

  mount_uploader :truck_photo, TruckPhotoUploader

  def self.search(query)
    where("to_tsvector(name) || ' ' || to_tsvector(description) @@ plainto_tsquery(?)", query)
  end

  def update_average_rating(rating)
    total_ratings = self.average_rating * (self.reviews.count - 1)
    total_ratings += rating
    self.average_rating = total_ratings.to_f / self.reviews.count
    self.save
  end
end

app/models/foodtruck.rb
class FoodTruck < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :food_truck
end

app/models/meal_time.rb
module MealTime
  def self.get_meal_time
    # Breakfast: 6-10AM; Lunch 10AM-3PM; Dinner: 3-11PM; Late Night: 11PM-12AM
    hour = Time.now.getlocal.hour
    meal = "None"
    if hour >= 6 && hour < 10
      meal = "Breakfast"
    elsif hour >= 10 && hour < 15
      meal = "Lunch"
    elsif hour >= 15 && hour < 23
      meal = "Dinner"
    elsif hour >= 23
      meal = "Late Night"
    end
    meal
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :food_truck
  belongs_to :user
  has_many :votes, dependent: :destroy

  validates :rating, presence: true, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
    }, allow_nil: false

     paginates_per 10

  def upvote_count
    votes.where(vote: 'up').count
  end

  def downvote_count
    votes.where(vote: 'down').count
  end

  def cache_vote_count
    self.votes_count = upvote_count - downvote_count
    save
  end

  after_create do
    self.food_truck.update_average_rating(self.rating)
    current = self.food_truck.average_rating *
    (self.food_truck.reviews.count - 1)
    current += self.rating
    self.food_truck.average_rating = current /
    self.food_truck.reviews.count
    self.food_truck.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def send_email
    Review.new_review_email(self).deliver
  end

  mount_uploader :profile_photo, ProfilePhotoUploader

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :user_id, presence: true
  validates :review_id, presence: true
  validates :vote, inclusion: { in: ["none", "up", "down"] }

  after_save do
    review.cache_vote_count
  end
end

app/controllers/admin/food_trucks_controller.rb
class Admin::FoodTrucksController < ApplicationController

  before_action :authorize_user

  def index
    @food_trucks = FoodTruck.order(:created_at)
  end

  def show
    @food_truck = FoodTruck.find(params[:id])
    @reviews = @food_truck.reviews.order(:created_at)
  end

  def destroy
    if FoodTruck.find(params[:id]).destroy
      flash[:notice] = "Successfully deleted food truck."
    else
      flash[:alert] = "Failed to remove food truck."
    end
    redirect_to admin_root
  end

  def authorize_user
    unless user_signed_in? && current_user.admin
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authorize_user

  def destroy
    review = Review.find(params[:id])
    food_truck = review.food_truck
    if review.destroy
      flash[:notice] = "Successfully deleted review."
    else
      flash[:alert] = "Failed to remove review."
    end
    redirect_to admin_food_truck_path(food_truck)
  end

  def authorize_user
    unless user_signed_in? and current_user.admin
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :profile_photo]
  end
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      @food_trucks = FoodTruck.includes(reviews: :user).search(params[:search][:query]).page(params[:page])
    else
      @food_trucks = FoodTruck.includes(reviews: :user).order(average_rating: :desc).page(params[:page])
    end
    @reviews = Review.all.sample(5)
    @jumbotron = true
  end

  def show
    @food_truck = FoodTruck.includes(reviews: [:user, :votes]).order("reviews.votes_count desc").find(params[:id])
    @food_trucks = FoodTruck.all.sample(4)
    @reviews = @food_truck.reviews.order(votes_count: :desc).page(params[:page])

    meal = MealTime.get_meal_time

    @location = Location.where(food_truck_id: @food_truck.id,
                               day_of_week: Time.now.getlocal.strftime('%A'),
                               time_of_day: meal)

    if @location.size == 0
      @location = "Boston,MA"
    else
      @location = @location.first.coordinates
    end
  end

  def new
    @food_truck = FoodTruck.new
  end

  def create
    @food_truck = FoodTruck.new(food_truck_params)

    @food_truck.user_id = current_user.id

    if @food_truck.save
      redirect_to @food_truck
    else
      if @food_truck.errors.messages[:name][0] == "can't be blank"
        flash.now[:notice] = "Your food truck was not succesfully submitted."
      elsif @food_truck.errors.messages[:name][0] == "has already been taken"
        flash.now[:notice] = "This food truck already exists."
      end
      render :new
    end
  end

  private

  def food_truck_params
    params.require(:food_truck).permit(:name, :website, :description, :truck_photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!

  def new
    @food_truck = FoodTruck.find(params[:food_truck_id])
    if @food_truck.reviews.where(user: current_user)
      @review = Review.new
    else
      flash[:notice] = "You have already reviewed this food truck!"
      redirect_to @food_truck
    end
  end

  def create
    @review = Review.new(review_params)
    @food_truck = FoodTruck.find(params[:food_truck_id])
    @review.user_id = current_user.id
    @review.food_truck_id = @food_truck.id



    if @review.save
      ReviewMailer.new_review_email(@review).deliver
      ReviewMailer.your_review_email(@review, current_user).deliver

      redirect_to @food_truck
    else
      flash.now[:notice] = "Your review was not succesfully submitted."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!

  def create
    review = Review.find(params[:review_id])
    vote = Vote.find_by(review: review, user: current_user)
    vote ||= Vote.new(review: review, user: current_user)
    vote.assign_attributes(vote_params)
    vote.save

    redirect_to review.food_truck
  end

  private

  def vote_params
    params.require(:vote).permit(:vote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/admin/food_trucks/index.html.erb
<% @food_trucks.each do |food_truck| %>
  <%= link_to admin_food_truck_path(food_truck), method: :delete do %>
    &#10006;
  <% end %> &nbsp;
  <%= link_to food_truck.name, admin_food_truck_path(food_truck) %>
  <br>
<% end %>

app/views/admin/food_trucks/show.html.erb
<h2><%= @food_truck.name %></h2>

<% @reviews.each do |r| %>
  <%= link_to admin_review_path(r.id), method: :delete do %>
    &#10006;
  <% end %>
  Posted by: <%= r.user.first_name + " " + r.user.last_name %><br>
  Created at: <%= r.created_at.getlocal.strftime("%I:%M%p, %m/%d/%Y") %><br>
  Rating: <% r.rating.to_i.times do %>&#9733; <% end %><br>
  <%= r.body %>
  <br>
  <br>
<% end %>

app/views/food_trucks/index.html.erb
<div class='index-blades'>
  <% if !@food_trucks.empty? %>
    <% @food_trucks.each do |food_truck| %>
      <div class="food-trucks-blade">
        <h4>
          <%= image_tag(food_truck.truck_photo.url(:thumb)) %>
          <div class="stars">
            <% food_truck.average_rating.round.times do %><%= image_tag('star.png') %><% end %>
          </div>
          (<%= food_truck.average_rating.round(1) %>)
          <%= link_to food_truck.name, food_truck %> -
          <% if food_truck.reviews.size != 0 %>
            <small>
              <%= link_to "#{food_truck.reviews.size} reviews", food_truck %>
            </small>
          <% end %>
        </h4>
        <% if food_truck.reviews.size != 0 %>
          <%= image_tag(food_truck.reviews.last.user.profile_photo, class: 'review-thumb') %>
          <div class="stars">
            <% food_truck.reviews.last.rating.times do %><% end %>
          </div>
          <span class="yellow">
            <%= food_truck.reviews.last.user.first_name + " " + food_truck.reviews.last.user.last_name %>
          </span>
          <br>
          <%= "#{food_truck.reviews.last.body.split('.')[0..3].join('.')}..." %>
        <% end %>
      </div>
    <% end %>

    <%= paginate @food_trucks, window: 2 %>
  <% end %>
</div>

<div class="right">
  <h3>Latest Reviews</h3>
  <% if @reviews.size != 0 %>
    <% @reviews.each do |r| %>
      <div class="latest-review">
        <%= image_tag(r.user.profile_photo) %>
        <div class="stars">
          <% r.rating.times do %><%= image_tag('star.png') %><% end %>
        </div>
        <%= link_to r.food_truck.name, food_truck_path(r.food_truck) %><br>
        <span class="yellow">
          <%= r.user.first_name + " " + r.user.last_name %>
        </span><br>
        <%= r.body %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/food_trucks/new.html.erb
<%= simple_form_for(@food_truck, html: {class: 'form-signin'}) do |f| %>
  <h3 class="yellow">Add A Food Truck</h3>

  <%= f.input :name,
              label: false,
              placeholder: 'Name',
              required: true,
              input_html: {class: 'form-control'} %>
  <br>
  <%= f.input :truck_photo,
              type: :file,
              input_html: { class: 'form-control'} %>
  <br>
  <%= f.input :website,
              label: false,
              placeholder: 'Website',
              input_html: {class: 'form-control'} %>
  <br>
  <%= f.input :description,
              label: false,
              placeholder: 'Description',
              required: true,
              input_html: {class: 'form-control'} %>
  <br>
  <%= f.button :submit,
               value: 'Create Food Truck',
               class: 'btn btn-lg btn-warning btn-block' %>

<% end %>

app/views/food_trucks/show.html.erb
<div class="food-truck-show-profile">
  <div class="map">
    <%= image_tag(@food_truck.truck_photo) %>
    <iframe src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_KEY'] %>&q=<%= @location %>" width="480" height="300" frameborder="0" style="border:0"></iframe>
  </div>
</div>

<div class='food-truck-show-reviews'>
  <%= link_to "Create a New Review!", new_food_truck_review_path(@food_truck), class: 'btn btn-warning btn-lg buttonright' %>
  <h2 class="orange"><%= @food_truck.name %></h2>

  <%= link_to @food_truck.website, @food_truck.website %>
  <div class="stars1">
    <h4><% @food_truck.average_rating.round.times do %><%= image_tag('star.png') %><% end %>
    (<%= @food_truck.average_rating.round(1) %>)</h4>
  </div>
  <%= @food_truck.description %>
  <br><br>
  <% @reviews.each do |r| %>
    <div class='food-truck-review-blade'>
      <% if r.votes.where(user_id: current_user, vote: 'up').size > 0 %>
        <div class="vote">
          <%= image_tag('up.png') %> <%= link_to image_tag('down-disabled.png'), review_votes_path(r, r.votes.where(user_id: current_user).first.id, vote: { vote: "down" } ), method: :post %>
        </div>
      <% elsif r.votes.where(user_id: current_user, vote: 'down').size > 0 %>
        <div class="vote">
          <%= link_to image_tag('up-disabled.png'), review_votes_path(r, r.votes.where(user_id: current_user).first.id, vote: { vote: "up" } ), method: :post %> <%= image_tag('down.png') %>
        </div>
      <% else %>
        <div class="vote">
          <%= link_to image_tag('up.png'), review_votes_path(r, vote: { vote: "up" } ), method: :post %>
          <%= link_to image_tag('down.png'), review_votes_path(r, vote: { vote: "down" } ), method: :post %>
        </div>
      <% end %>
      <%= image_tag(r.user.profile_photo) %>
      <div class="stars">
        <% r.rating.to_i.times do %><%= image_tag('star.png') %><% end %>
      </div>
      <span class="orange">
        <%= r.user.first_name + " " + r.user.last_name %>
      </span>
       at: <%= r.created_at.getlocal.strftime("%I:%M%p, %m/%d/%Y") %><br>
      <span class="yellow">Upvotes: <%= r.votes.where(vote: 'up').count %> / Downvotes:
      <%= r.votes.where(vote: 'down').count %><br></span>
      <%= r.body %>
    </div>
  <% end %>
  <%= paginate @reviews, window: 2%>
</div>

<div class="right">
  <h3>Try these food trucks!</h3>
  <% if @food_trucks.size != 0 %>
    <% @food_trucks.each do |t| %>
      <div class="latest-review">
        <%= image_tag(t.truck_photo.url(:thumb)) %>
        <div class="stars">
          <% t.average_rating.ceil.times do %><%= image_tag('star.png') %><% end %>
        </div>
        <%= link_to t.name, t %><br>
        <%= t.description %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What The Truck?</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= image_tag('title1.png') %></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= simple_form_for :search, url: food_trucks_path(:index), html: {class: 'navbar-form'}, method: :get do |f| %>
              <%= f.input :query, placeholder: "Search Trucks", label: false, input_html: { class:
          'form-control'} %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <% if current_user.profile_photo != "" %>
              <li><%= image_tag current_user.profile_photo, class: "navbar-avatar" %></li>
            <% else %>
              <li><a><%= "Signed in as " + current_user.first_name + " " + current_user.last_name %></a></li>
            <% end %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <% if @jumbotron %>
      <div class="jumbotron">
        <h1>your favorite truck stop</h1>
        <h3>Search our listings or add a truck!</h3>
        <p>
          <% if user_signed_in? %>
            <%= link_to 'Add a food truck', new_food_truck_path, class: 'btn btn-warning' %>
        <% else %>
            <%= link_to "Sign In", new_user_session_path, class: 'btn btn-lg btn-warning' %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-lg btn-warning' %>
        <% end %>
        </p>
      </div>
    <% end %>

    <% if flash.any? %>
      <div class="alert alert-warning" role="alert">
        <strong>
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </strong>
      </div>
    <% end %>

    <div class="main">

      <%= yield %>

    </div>

  </div>

  <div class="container text-center">
  <hr>
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-pills nav-justified">
                <li><a href="https://github.com/Maimer/what_the_truck">GitHub Repository</a></li>
                <li><a href="https://github.com/Maimer/">Nick Lee</a></li>
                <li><a href="https://github.com/saltys/">Chris Saltys</a></li>
                <li><a href="https://github.com/briancox730/">Brian Cox</a></li>
            </ul>
        </div>
    </div>
</div>


</body>
</html>

app/views/reviews/new.html.erb
<%= simple_form_for([@food_truck, @review], html: {class: 'form-signin'}) do |f| %>
  <h3>Add A Review</h3>
  <%= f.input :rating,
              label: false,
              placeholder: 'Rating',
              required: true,
              input_html: { min: 1, max: 5, class: 'form-control' } %>
  <br>
  <%= f.input :body,
              label: false,
              placeholder: 'Your Review...',
              input_html: { rows: 7, class: 'form-control' } %>
  <br>
  <%= f.button :submit,
              value: 'Create Review',
              class: 'btn btn-lg btn-warning btn-block' %>
<% end %>